spring:
  application:
    name: server
  datasource:
    url: "jdbc:postgresql://database/postgres"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          discord:
            provider: discord
            client-id: YOUR_CLIENT_ID_HERE
            client-secret: YOUR_CLIENT_SECRET_HERE
            client-authentication-method: post
            authorization-grantType: authorization_code
            scope:
              - identify
            redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/login/oauth2/code/discord"
            client-name: Discord
        provider:
          discord:
            authorization-uri: https://discordapp.com/api/oauth2/authorize
            token-uri: https://discordapp.com/api/oauth2/token
            user-info-uri: https://discordapp.com/api/users/@me
            user-name-attribute: username

