spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/postgres"
  mail:
    host: 0.0.0.0
    port: 1025
    username: "test"
    password: "test"
    protocol: "smtp"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

keycloak:
  base-url: "http://0.0.0.0:9080"
  username: admin
  password: admin
  client-secret: G9ZGhl6wrmSaA5wsNJPw7CEofv8OW7MT
  initialize-on-startup: true
  grant-type: password

app:
  instance-owner:
    name: "local"
    password: "passy"
