spring:
  application:
    name: server
  datasource:
    url: "jdbc:postgresql://database/postgres"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          open-dme:
            client-id: YOUR_CLIENT_ID_HERE
            scope:
              - openid
              - profile
            client-secret: YOUR_CLIENT_SECRET_HERE
            authorization-grantType: authorization_code
            redirect-uri: "${keycloak.base-path}/login/oauth2/code/discord"
        provider:
          open-dme:
            token-uri: ${keycloak.base-path}/protocol/openid-connect/token
            authorization-uri: ${keycloak.base-path}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            jwk-set-uri: ${keycloak.base-path}/protocol/openid-connect/certs

keycloak:
  base-url: "http://0.0.0.0:8080"
  realm: "open-dme"
  base-path: ${keycloak.base-url}/auth/realms/${keycloak.realm}
