spring:
  application:
    name: server
  datasource:
    url: "jdbc:postgresql://0.0.0.0/postgres"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.base-url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          open-dme:
            client-id: "open-dme"
            client-secret: "RrWwT4xHHe3In0sZnRQ36ZuAwhWAxIc7"
            scope:
              - openid
              - profile
              - roles
            authorization-grant-type: authorization_code
            redirect-uri: "{baseScheme}://{baseHost}{basePort}/login/oauth2/code/open-dme"
        provider:
          open-dme:
            issuer-uri: "${keycloak.base-url}/realms/${keycloak.realm}"
            token-uri: ${keycloak.realm-url}/protocol/openid-connect/token
            authorization-uri: ${keycloak.realm-url}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            jwk-set-uri: ${keycloak.realm-url}/protocol/openid-connect/certs
  mail:
    host: mail
    port: 1025
    username: "test"
    password: "test"
    protocol: "smtp"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

qr-code:
  discover-url: "${keycloak.realm-url}/.well-known/openid-configuration"
  client-id: "${spring.security.oauth2.client.registration.open-dme.client-id}"
  client-secret: "${spring.security.oauth2.client.registration.open-dme.client-secret}"
  scope: "openid profile roles"
  host-name: "http://remote.host"

store-links:
  apple: "https://www.apple.com/"
  android: "https://play.google.com/store"

department:
  name: "Berlin-Mitte"
mail:
  subject: "Initial Passwort Open DME"

# http://0.0.0.0:9080/realms/open-dme/.well-known/openid-configuration
keycloak:
  initialize-on-startup: false
  base-url: "http://keycloak:8080"
  url: ${keycloak.base-url}/auth/
  realm-url: ${keycloak.url}realms/${keycloak.realm}
  master-realm: "master"
  realm: "open-dme"
  client-id: admin-cli
  client-secret: 123456789
  username: admin
  password: admin
  grant-type: password

app:
  instance-owner:
    name: "admin"
    password: "admin"

springdoc:
  swagger-ui:
    oauth:
      client-id: ${spring.security.oauth2.client.registration.open-dme.client-id}
