spring:
  application:
    name: server
  datasource:
    url: "jdbc:postgresql://database/postgres"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          open-dme:
            client-id: "open-dme"
            client-secret: U57todoX9MWXlr2irfa51cCdJfGGwxPZ
            scope:
              - openid
              - profile
            authorization-grantType: authorization_code
            redirect-uri: "{baseScheme}://{baseHost}{basePort}/login/oauth2/code/open-dme"
        provider:
          open-dme:
            token-uri: ${keycloak.realm-url}/protocol/openid-connect/token
            authorization-uri: ${keycloak.realm-url}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            jwk-set-uri: ${keycloak.realm-url}/protocol/openid-connect/certs

keycloak:
  base-url: "http://keycloak:8080"
  url: ${keycloak.base-url}/auth/
  realm-url: ${keycloak.url}/realms/${keycloak.realm}
  master-realm: "master"
  realm: "open-dme"
  client-id: admin-cli
  client-secret: 123456789
  initialize-on-startup: false

app:
  instance-owner:
    name: "admin"
    password: "admin"
