services:
  open-dme:
    image: ghcr.io/open-dme/open-dme-server
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./config/application.yml:/app/applications.yml:ro"
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "9080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_FEATURES:
      # KC_DB: "postgres"
      # KC_DB_USERNAME: "postgres"
      # KC_DB_PASSWORD: "postgres"
      # KC_DB_URL: jdbc:postgresql://localhost/keycloak
    command:
      - start-dev
      # - start
      # - --optimized
      # - --hostname-port=3000
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
  cache:
    image: redis

