services:
  open-dme:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    profiles: []
    ports:
      - "8080:8080"
    volumes:
      - "./config/application.yml:/app/applications.yml:ro"

  open-dme-prod:
    extends:
      service: open-dme
    image: ghcr.io/open-dme/open-dme-server
    profiles:
      - prod

  open-dme-dev:
    extends:
      service: open-dme
    profiles:
      - dev

  keycloak:
    image: quay.io/keycloak/keycloak
    profiles: []
    ports:
      - "9080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_FEATURES:

  keycloak-prod:
    extends:
      service: keycloak
    profiles:
      - prod
    environment:
      KC_DB: "postgres"
      KC_DB_USERNAME: "postgres"
      KC_DB_PASSWORD: "postgres"
      KC_DB_URL: jdbc:postgresql://localhost/keycloak
    command:
      - start
      - --optimized
      - --hostname-port=3000

  keycloak-dev:
    extends:
      service: keycloak
    profiles:
      - dev
    command:
      - start-dev
      - --verbose

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
  cache:
    image: redis

