services:
  open-dme:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    profiles: [none]
    ports:
      - "8888:8080"
    volumes:
      - "./config/application.yml:/app/applications.yml:ro"

  open-dme-prod:
    extends:
      service: open-dme
    image: ghcr.io/open-dme/open-dme-server
    profiles:
      - prod

  open-dme-dev:
    extends:
      service: open-dme
    profiles:
      - dev

  keycloak:
    image: quay.io/keycloak/keycloak
    profiles: [none]
    ports:
      - "9080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_FEATURES:
    volumes:
       - "./kc_data:/opt/keycloak/data/import"

  keycloak-prod:
    extends:
      service: keycloak
    profiles:
      - prod
    environment:
      KC_DB: "postgres"
      KC_DB_USERNAME: "postgres"
      KC_DB_PASSWORD: "postgres"
      KC_DB_URL: jdbc:postgresql://localhost/keycloak
    command:
      - start
      - --optimized
      - --hostname-port=8080
      - --import-realm

  keycloak-dev:
    extends:
      service: keycloak
    profiles:
      - dev
      - local
    command:
      - start-dev
      - --verbose
      - --import-realm
  database-dev:
    extends:
      service: database
    profiles:
      - dev
    ports:
      - "5432:5432"

  database:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"

  cache:
    image: redis

